version: '3.5'

# docker-compose -f docker-compose.yml -f upload-script.yml up -d

services:
  # ----------------------------------------------------------------------
  # EXTRACTORS
  # ----------------------------------------------------------------------

  # extract checksum
  uploadtestrun:
    image: tcnichol/testing-upload:latest
    restart: unless-stopped
    networks:
      - clowder_clowder
networks:
  clowder_clowder: